version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    ports: 
      - 5432:5432
  mongo:
    image: mongo
    ports: 
      - 27017:27017
  cache:
    image: redis
    ports: 
      - 6379:6379
    
